##### General settings
env: unset
oc_namespace: operator-pipeline-{{ env }}
service_account_name: operator-pipeline-admin
suffix: "{{ env }}"

operator_pipeline_private_key_local_path: ../../vaults/{{ env }}/operator-pipeline.key
operator_pipeline_private_cert_local_path: ../../vaults/{{ env }}/operator-pipeline.pem
