---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: content-hash
spec:
  params:
    - name: bundle_path
  results:
    - name: md5sum
  workspaces:
    - name: source
  steps:
    - name: compute-md5sum
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        set -xe
        echo "Compute md5hash of bundle content..."

        find $(params.bundle_path) -not -name "Dockerfile" -type f -printf '%f\t%p\n' | \
          sort -V -k1 | \
          cut -d$'\t' -f2 | \
          tr '\n' '\0' | \
          xargs -r0 -I {} md5sum "{}" >> hashes.txt

        cat hashes.txt

        md5sum hashes.txt | awk '{ print $1 }' | tee $(results.md5sum.path)
